CREATE TABLE RETAIL_CUSTOMERS (CUSTOMER_ID INT, CUSTOMER_FNAME VARCHAR2(50), CUSTOMER_LNAME VARCHAR2(50));
CREATE TABLE RETAIL_TRANSACTIONS (TRANSACTION_ID INT,CUSTOMER_ID INT ,TRANSACTION_DATE DATE,TRANSACTION_AMOUNT INT);
INSERT INTO RETAIL_CUSTOMERS(CUSTOMER_ID,CUSTOMER_FNAME,CUSTOMER_LNAME) values (1,'CustomerF','CustomerL');
INSERT INTO RETAIL_CUSTOMERS(CUSTOMER_ID,CUSTOMER_FNAME,CUSTOMER_LNAME) values (2,'Ril','Ret');
<<<<<<< HEAD
=======
<<<<<<< HEAD
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (1,1,'2025-02-07',120);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (2,1,'2025-03-05',85);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (3,1,'2025-03-02',160);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (4,1,'2025-04-01',90);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (5,1,'2025-05-06',120);
=======
>>>>>>> feature
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (1,1,'2025-05-10',105);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (2,1,'2025-04-15',60);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (3,1,'2025-04-30',160);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (4,1,'2025-04-03',65);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (5,1,'2025-02-15',150);
<<<<<<< HEAD
=======
>>>>>>> 4468398 (commit changes)
>>>>>>> feature
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (6,2,'2025-03-12',105);
INSERT INTO RETAIL_TRANSACTIONS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,TRANSACTION_AMOUNT) VALUES (7,2,'2023-03-08',10);
COMMIT;